---
title: "SVG Test"
format: html
editor: visual
---

## Embed SVG in Doc


```{r}
library(svglite)

svglite("hist.svg", width = 4, height = 4, standalone=F)
x <- iris$Sepal.Length
par( mar=c(0,0,0,0) )
hist( x, axes=F, ann=FALSE, col="steelblue", border="white" ) 
dev.off()

# copy and paste resulting code into doc below
```

The function **svgstring** captures text version directly. 

```{r}
s <- svgstring( width = 2, height = 2, standalone=F )
par( mar=c(0,0,0,0) )
hist( x, axes=F, ann=FALSE, col="steelblue", border="white" ) 
dev.off() 

s()
```


## Adding to QMD

Customize by adding class='hist' to a DIV tag: 

```{=html}
<div class='hist'>
<svg class='svglite' width='288.00pt' height='288.00pt' viewBox='0 0 288.00 288.00'>
<defs>
  <style type='text/css'><![CDATA[
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  ]]></style>
</defs>
<rect width='100%' height='100%' style='stroke: none; fill: #FFFFFF;'/>
<defs>
  <clipPath id='cpMC4wMHwyODguMDB8MC4wMHwyODguMDA='>
    <rect x='0.00' y='0.00' width='288.00' height='288.00' />
  </clipPath>
</defs>
<g clip-path='url(#cpMC4wMHwyODguMDB8MC4wMHwyODguMDA=)'>
<rect x='10.67' y='234.32' width='33.33' height='43.01' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='44.00' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='77.33' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='110.67' y='19.27' width='33.33' height='258.06' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='144.00' y='10.67' width='33.33' height='266.67' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='177.33' y='122.49' width='33.33' height='154.84' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='210.67' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='244.00' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
</g>
</svg>
</div>
```


<br>
<hr>
<br>


<svg class='svglite' width='288.00pt' height='288.00pt' viewBox='0 0 288.00 288.00'>
<defs>
  <style type='text/css'><![CDATA[
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  ]]></style>
</defs>
<rect width='100%' height='100%' style='stroke: none; fill: #FFFFFF;'/>
<defs>
  <clipPath id='cpMC4wMHwyODguMDB8MC4wMHwyODguMDA='>
    <rect x='0.00' y='0.00' width='288.00' height='288.00' />
  </clipPath>
</defs>
<g clip-path='url(#cpMC4wMHwyODguMDB8MC4wMHwyODguMDA=)'>
<rect x='10.67' y='234.32' width='33.33' height='43.01' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='44.00' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='77.33' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='110.67' y='19.27' width='33.33' height='258.06' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='144.00' y='10.67' width='33.33' height='266.67' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='177.33' y='122.49' width='33.33' height='154.84' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='210.67' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='244.00' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
</g>
</svg>


<br>
<hr>
<br>




```{r}
x <- 
"<svg class='svglite' width='288.00pt' height='288.00pt' viewBox='0 0 288.00 288.00'>
<defs>
  <style type='text/css'><![CDATA[
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  ]]></style>
</defs>
<rect width='100%' height='100%' style='stroke: none; fill: #FFFFFF;'/>
<defs>
  <clipPath id='cpMC4wMHwyODguMDB8MC4wMHwyODguMDA='>
    <rect x='0.00' y='0.00' width='288.00' height='288.00' />
  </clipPath>
</defs>
<g clip-path='url(#cpMC4wMHwyODguMDB8MC4wMHwyODguMDA=)'>
<rect x='10.67' y='234.32' width='33.33' height='43.01' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='44.00' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='77.33' y='45.08' width='33.33' height='232.26' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='110.67' y='19.27' width='33.33' height='258.06' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='144.00' y='10.67' width='33.33' height='266.67' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='177.33' y='122.49' width='33.33' height='154.84' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='210.67' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
<rect x='244.00' y='225.72' width='33.33' height='51.61' style='stroke-width: 0.75; stroke: #FFFFFF; fill: #4682B4;' />
</g>
</svg>"
```

```{r, results="asis", fig.width=8}
cat( x )
```



<br>
<hr>
<br>


`r x`


<br>
<hr>
<br>


```
<style>

svg {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 250px;
  height: 150px;
}

.hist svg {width: 10%; height: auto;}

</style>
```


```{=html}
<style>

svg {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 250px;
  height: 150px;
}

.hist svg {width: 10%; height: auto;}

</style>
```


```{r, eval=F, echo=F}

.svglite svg {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
  height: 150px;
}

svg {width: 100%; height: auto;}


```

